### ISSUE TITLE
[Question] Full PHP vs PHP-CLI

### ISSUE THREAD

**Issue by MrGiga** [ipunkt/docker-laravel-queue-worker#5]
Is there any reason you went with full php rather then just php-cli?

I am probably missing something and apologies if I am.

**Comment by rokde** [comment]
There is no particular reason. It was the easiest way because our laravel frontend image was mostly the same in the beginning.

So when you can make a pull request with your wish we will look at it and maybe merge.

**Comment by MrGiga** [comment]
I was able to implement it but found that I could not implement the msodbcsql driver with alpine. So I had to scratch my implementation, although if you still want to see it, I can put in a pull request.

**Comment by rokde** [comment]
We do not do anything with mssql or odbc. so maybe you should fork it to suit your needs. We won't merge it, because we do not need mssql at the time of writing. sorry.
